manifest-version = 1

[component]
name = "Eulerian Analytics"
version = "1.1.1"
category = "data-collection"
subcategory = "analytics"
description = '''
Eulerian Analytics component allowing to integrate the [Eulerian Marketing Platform](https://eulerian.com) through the [Edgee](https://www.edgee.cloud) platform : 100% privacy by design, data sovereignty, analytics, attribution, user segmentation & data activation.

You can start with a [free account](https://eulerian.io)
'''
documentation = "https://github.com/EulerianTechnologies/edgee-eulerian-analytics"
repository = "https://github.com/EulerianTechnologies/edgee-eulerian-analytics"
language = "JavaScript"
wit-version = "0.5.0"
icon-path = "eulerian-analytics.png"

[component.build]
command = "npm install && npm run generate && npm run build"
output_path = "./eulerian-analytics.wasm"

[component.settings.trackingTarget]
title = "Tracking Domain Target"
type = "string"
required = true
description = "This is the name of domain target you are going to send the data to"

[component.settings.website]
title = "Name of the website"
type = "string"
required = true
description = "Name of the website to which data will be sent"
